--IP Functional Simulation Model
--VERSION_BEGIN 12.1SP1 cbx_mgl 2013:01:31:18:08:38:SJ cbx_simgen 2013:01:31:18:04:55:SJ  VERSION_END


-- Copyright (C) 1991-2012 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- You may only use these simulation model output files for simulation
-- purposes and expressly not for synthesis or any other purposes (in which
-- event Altera disclaims all warranties of any kind).


--synopsys translate_off

--synthesis_resources = lut 3 mux21 9 
 LIBRARY ieee;
 USE ieee.std_logic_1164.all;

 ENTITY  niosII_system_nios2_qsys_0_data_master_translator IS 
	 PORT 
	 ( 
		 av_address	:	IN  STD_LOGIC_VECTOR (24 DOWNTO 0);
		 av_byteenable	:	IN  STD_LOGIC_VECTOR (3 DOWNTO 0);
		 av_debugaccess	:	IN  STD_LOGIC;
		 av_read	:	IN  STD_LOGIC;
		 av_readdata	:	OUT  STD_LOGIC_VECTOR (31 DOWNTO 0);
		 av_waitrequest	:	OUT  STD_LOGIC;
		 av_write	:	IN  STD_LOGIC;
		 av_writedata	:	IN  STD_LOGIC_VECTOR (31 DOWNTO 0);
		 clk	:	IN  STD_LOGIC;
		 reset	:	IN  STD_LOGIC;
		 uav_address	:	OUT  STD_LOGIC_VECTOR (24 DOWNTO 0);
		 uav_burstcount	:	OUT  STD_LOGIC_VECTOR (2 DOWNTO 0);
		 uav_byteenable	:	OUT  STD_LOGIC_VECTOR (3 DOWNTO 0);
		 uav_debugaccess	:	OUT  STD_LOGIC;
		 uav_lock	:	OUT  STD_LOGIC;
		 uav_read	:	OUT  STD_LOGIC;
		 uav_readdata	:	IN  STD_LOGIC_VECTOR (31 DOWNTO 0);
		 uav_readdatavalid	:	IN  STD_LOGIC;
		 uav_waitrequest	:	IN  STD_LOGIC;
		 uav_write	:	OUT  STD_LOGIC;
		 uav_writedata	:	OUT  STD_LOGIC_VECTOR (31 DOWNTO 0)
	 ); 
 END niosII_system_nios2_qsys_0_data_master_translator;

 ARCHITECTURE RTL OF niosII_system_nios2_qsys_0_data_master_translator IS

	 ATTRIBUTE synthesis_clearbox : natural;
	 ATTRIBUTE synthesis_clearbox OF RTL : ARCHITECTURE IS 1;
	 SIGNAL	niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_end_begintransfer_229q	:	STD_LOGIC := '0';
	 SIGNAL	niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_212q	:	STD_LOGIC := '0';
	 SIGNAL	niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_write_accepted_228q	:	STD_LOGIC := '0';
	 SIGNAL  wire_nO_w300w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_nO_w296w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_nO_w293w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_av_waitrequest_216m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_av_waitrequest_217m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_end_begintransfer_226m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_end_begintransfer_227m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_204m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_207m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_208m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_write_accepted_210m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_write_accepted_211m_dataout	:	STD_LOGIC;
	 SIGNAL  wire_w_lg_reset291w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_uav_readdatavalid295w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_uav_waitrequest288w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_internal_begintransfer_224_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_uav_read_219_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_uav_write_221_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_vcc :	STD_LOGIC;
 BEGIN

	wire_w_lg_reset291w(0) <= NOT reset;
	wire_w_lg_uav_readdatavalid295w(0) <= NOT uav_readdatavalid;
	wire_w_lg_uav_waitrequest288w(0) <= NOT uav_waitrequest;
	av_readdata <= ( uav_readdata(31 DOWNTO 0));
	av_waitrequest <= wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_av_waitrequest_217m_dataout;
	s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_internal_begintransfer_224_dataout <= ((s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_uav_read_219_dataout OR s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_uav_write_221_dataout) AND wire_nO_w300w(0));
	s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_uav_read_219_dataout <= (av_read AND wire_nO_w296w(0));
	s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_uav_write_221_dataout <= (av_write AND wire_nO_w293w(0));
	s_wire_vcc <= '1';
	uav_address <= ( av_address(24 DOWNTO 0));
	uav_burstcount <= ( "1" & "0" & "0");
	uav_byteenable <= ( av_byteenable(3 DOWNTO 0));
	uav_debugaccess <= av_debugaccess;
	uav_lock <= '0';
	uav_read <= s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_uav_read_219_dataout;
	uav_write <= s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_uav_write_221_dataout;
	uav_writedata <= ( av_writedata(31 DOWNTO 0));
	PROCESS (clk, reset)
	BEGIN
		IF (reset = '1') THEN
				niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_end_begintransfer_229q <= '0';
				niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_212q <= '0';
				niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_write_accepted_228q <= '0';
		ELSIF (clk = '1' AND clk'event) THEN
				niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_end_begintransfer_229q <= wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_end_begintransfer_227m_dataout;
				niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_212q <= wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_208m_dataout;
				niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_write_accepted_228q <= wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_write_accepted_211m_dataout;
		END IF;
	END PROCESS;
	wire_nO_w300w(0) <= NOT niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_end_begintransfer_229q;
	wire_nO_w296w(0) <= NOT niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_212q;
	wire_nO_w293w(0) <= NOT niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_write_accepted_228q;
	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_av_waitrequest_216m_dataout <= ((uav_waitrequest OR s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_internal_begintransfer_224_dataout) AND wire_nO_w293w(0)) OR NOT(av_write);
	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_av_waitrequest_217m_dataout <= wire_w_lg_uav_readdatavalid295w(0) WHEN av_read = '1'  ELSE wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_av_waitrequest_216m_dataout;
	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_end_begintransfer_226m_dataout <= niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_end_begintransfer_229q AND uav_waitrequest;
	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_end_begintransfer_227m_dataout <= wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_end_begintransfer_226m_dataout OR (uav_waitrequest AND s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_internal_begintransfer_224_dataout);
	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_204m_dataout <= niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_212q AND NOT((uav_readdatavalid AND niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_212q));
	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_207m_dataout <= (wire_w_lg_uav_waitrequest288w(0) AND av_read) AND wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_av_waitrequest_217m_dataout;
	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_208m_dataout <= wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_204m_dataout WHEN niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_212q = '1'  ELSE wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_read_accepted_207m_dataout;
	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_write_accepted_210m_dataout <= niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_write_accepted_228q OR (wire_w_lg_uav_waitrequest288w(0) AND s_wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_uav_write_221_dataout);
	wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_write_accepted_211m_dataout <= wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_write_accepted_210m_dataout AND wire_niosii_system_nios2_qsys_0_data_master_translator_altera_merlin_master_translator_nios2_qsys_0_data_master_translator_av_waitrequest_217m_dataout;

 END RTL; --niosII_system_nios2_qsys_0_data_master_translator
--synopsys translate_on
--VALID FILE
